/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_shygoo_jxgamepads_JXGamepads */

#ifndef _Included_net_shygoo_jxgamepads_JXGamepads
#define _Included_net_shygoo_jxgamepads_JXGamepads
#ifdef __cplusplus
extern "C" {
#endif
#undef net_shygoo_jxgamepads_JXGamepads_MAX_GAMEPADS
#define net_shygoo_jxgamepads_JXGamepads_MAX_GAMEPADS 4L
#undef net_shygoo_jxgamepads_JXGamepads_MAX_BUTTONS
#define net_shygoo_jxgamepads_JXGamepads_MAX_BUTTONS 16L
#undef net_shygoo_jxgamepads_JXGamepads_MAX_AXES
#define net_shygoo_jxgamepads_JXGamepads_MAX_AXES 6L
#undef net_shygoo_jxgamepads_JXGamepads_GAMEPAD_0
#define net_shygoo_jxgamepads_JXGamepads_GAMEPAD_0 0L
#undef net_shygoo_jxgamepads_JXGamepads_GAMEPAD_1
#define net_shygoo_jxgamepads_JXGamepads_GAMEPAD_1 1L
#undef net_shygoo_jxgamepads_JXGamepads_GAMEPAD_2
#define net_shygoo_jxgamepads_JXGamepads_GAMEPAD_2 2L
#undef net_shygoo_jxgamepads_JXGamepads_GAMEPAD_3
#define net_shygoo_jxgamepads_JXGamepads_GAMEPAD_3 3L
#undef net_shygoo_jxgamepads_JXGamepads_AXIS_LTRIGGER
#define net_shygoo_jxgamepads_JXGamepads_AXIS_LTRIGGER 0L
#undef net_shygoo_jxgamepads_JXGamepads_AXIS_RTRIGGER
#define net_shygoo_jxgamepads_JXGamepads_AXIS_RTRIGGER 1L
#undef net_shygoo_jxgamepads_JXGamepads_AXIS_LSTICK_X
#define net_shygoo_jxgamepads_JXGamepads_AXIS_LSTICK_X 2L
#undef net_shygoo_jxgamepads_JXGamepads_AXIS_LSTICK_Y
#define net_shygoo_jxgamepads_JXGamepads_AXIS_LSTICK_Y 3L
#undef net_shygoo_jxgamepads_JXGamepads_AXIS_RSTICK_X
#define net_shygoo_jxgamepads_JXGamepads_AXIS_RSTICK_X 4L
#undef net_shygoo_jxgamepads_JXGamepads_AXIS_RSTICK_Y
#define net_shygoo_jxgamepads_JXGamepads_AXIS_RSTICK_Y 5L
/*
 * Class:     net_shygoo_jxgamepads_JXGamepads
 * Method:    xgIsConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_shygoo_jxgamepads_JXGamepads_xgIsConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_shygoo_jxgamepads_JXGamepads
 * Method:    xgGetAxes
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_shygoo_jxgamepads_JXGamepads_xgGetAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_shygoo_jxgamepads_JXGamepads
 * Method:    xgGetButtons
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_shygoo_jxgamepads_JXGamepads_xgGetButtons
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_shygoo_jxgamepads_JXGamepads
 * Method:    xgSetVibration
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_net_shygoo_jxgamepads_JXGamepads_xgSetVibration
  (JNIEnv *, jclass, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
