/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_shygoo_jconsolecolors_JConsoleColors */

#ifndef _Included_net_shygoo_jconsolecolors_JConsoleColors
#define _Included_net_shygoo_jconsolecolors_JConsoleColors
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_shygoo_jconsolecolors_JConsoleColors
 * Method:    setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_shygoo_jconsolecolors_JConsoleColors_setColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_shygoo_jconsolecolors_JConsoleColors
 * Method:    getColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_shygoo_jconsolecolors_JConsoleColors_getColor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
